{% set name = "flyteidl" %}
{% set version = "0.24.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flyteidl-{{ version }}.tar.gz
  sha256: cfc9ef30dbe04843aef4fa28fe70e69d1cf13b09de7d26c5ea4590726fcc44c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - googleapis-common-protos
    - protobuf >=3.5.0,<4.0.0
    - protoc-gen-swagger
    - python >=3.6

test:
  imports:
    - flyteidl
    - flyteidl.admin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/flyteorg/flyteidl
  summary: IDL for Flyte Platform
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - bmcconeghy
    - asford
